config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index', as: 'contacts'
  get 'contacts/new', as: 'new_contact'
  post 'contacts/create', as: 'create_contact'
  get 'contacts/:id/edit', to: 'contacts#edit', as: 'edit_contact'
  patch 'contacts/:id/update', to: 'contacts#update', as: 'update_contact'
  root 'contacts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :group

  paginates_per 10

  validates :name, :email, :group_id, presence: true
  validates :name, length: { minimum: 2 }

  has_attached_file :avatar, styles: { medium: "150x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def gravatar
    hash = Digest::SHA256.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    if params[:group_id] && !params[:group_id].empty?
      # @contacts = Contact.where(group_id: params[:group_id]).page(params[:page])
      @contacts = Group.find(params[:group_id]).contacts.order(created_at: :desc).page(params[:page])
    else
      @contacts = Contact.order(created_at: :desc).page(params[:page])
    end
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
        flash[:success] = "Contact was successfully created."
        redirect_to contacts_path
    else
        render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      flash[:success] = "Contact was successfully updated."
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :company, :address, :phone, :group_id, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td class="middle">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= contact.avatar.present? ? image_tag("/system/contacts/avatars/000/000/121/thumb/#{contact.avatar_file_name}", class: "media-object", style: "width:100px; height:100px") : image_tag("/system/contacts/avatars/000/000/121/thumb/default.png", class: "media-object", style: "width:100px; height:100px") %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= contact.name %></h4>
        <address>
          <strong><%= contact.company %></strong><br>
          <%= contact.email %>
        </address>
      </div>
    </div>
  </td>
  <td width="100" class="middle">
    <div>
      <%= link_to edit_contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: "Edit" do %>
        <i class="glyphicon glyphicon-edit"></i>
      <% end %>
      <a href="#" class="btn btn-circle btn-danger btn-xs" title="Edit">
        <i class="glyphicon glyphicon-remove"></i>
      </a>
    </div>
  </td>
</tr>

app/views/contacts/_form.html.erb
<%= form_for(@contact, url: @contact.new_record? ? create_contact_path : update_contact_path(@contact), html: { multipart: true }) do |f| %>

  <div class="panel-body">

    <% if @contact.errors.any? %>
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-danger">
            <h3>Please correct this following errors:</h3>

            <ul>
              <% @contact.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-horizontal">
      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <%= f.label :name, class: "control-label col-md-3" %>
            <div class="col-md-8">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :company, class: "control-label col-md-3" %>
            <div class="col-md-8">
              <%= f.text_field :company, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, class: "control-label col-md-3" %>
            <div class="col-md-8">
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :phone, class: "control-label col-md-3" %>
            <div class="col-md-8">
              <%= f.text_field :phone, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :company, class: "control-label col-md-3" %>
            <div class="col-md-8">
              <%= f.text_field :company, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :address, class: "control-label col-md-3" %>
            <div class="col-md-8">
              <%= f.text_area :address, class: "form-control", rows: 3 %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :group_id, class: "control-label col-md-3" %>
            <div class="col-md-5">
              <%= f.collection_select :group_id, Group.all, :id, :name, { prompt: "Select Group" }, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
            </div>
          </div>
          <div class="form-group" id="add-new-group" style="display: none;">
            <div class="col-md-offset-3 col-md-8">
              <div class="input-group">
                <input type="text" name="new_group" id="new_group" class="form-control">
                <span class="input-group-btn">
                  <a href="#" class="btn btn-default">
                    <i class="glyphicon glyphicon-ok"></i>
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="fileinput fileinput-new" data-provides="fileinput">
            <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
              <% if @contact.avatar_file_name.present? %> 
                <%= image_tag "/system/contacts/avatars/#{@contact.id.to_s.rjust(9, '0').scan(/.{3}/).join('/')}/medium/#{@contact.avatar_file_name}", style: "width:150px; height:150px" %>
              <% else %>
                <%= image_tag "/system/contacts/avatars/000/000/121/medium/default.png" %>
              <% end %>
            </div>
            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 150px; max-height: 150px;"></div>
            <div class="text-center">
              <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
              <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-offset-3 col-md-6">
            <%= f.submit @contact.new_record? ? "Save" : "Update", class: "btn btn-primary" %>
            <a href="#" class="btn btn-default">Cancel</a>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Edit Contact</strong>
  </div>
    <%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<% if @contacts.blank? %>
  <div class="alert alert-warning">
    <strong>Record Not Found</strong>
  </div>
<% end %>

<div class="panel panel-default">
  <table class="table">
    <%= render @contacts %>
  </table>            
</div>

<div class="text-center">
  <%= paginate @contacts%>
</div>

app/views/contacts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Add Contact</strong>
  </div>

    <form action="/contacts/create" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="panel-body">

        <% if @contact.errors.any? %>
          <div class="row">
            <div class="col-md-12">
              <div class="alert alert-danger">
                <h3>Please correct this following errors:</h3>

                <ul>
                  <% @contact.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>

        <div class="form-horizontal">
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label for="name" class="control-label col-md-3">Name</label>
                <div class="col-md-8">
                  <input type="text" name="contact[name]" id="name" class="form-control">
                </div>
              </div>
              <div class="form-group">
                <label for="company" class="control-label col-md-3">Company</label>
                <div class="col-md-8">
                  <input type="text" name="contact[company]" id="company" class="form-control">
                </div>
              </div>
              <div class="form-group">
                <label for="email" class="control-label col-md-3">Email</label>
                <div class="col-md-8">
                  <input type="text" name="contact[email]" id="email" class="form-control">
                </div>
              </div>
              <div class="form-group">
                <label for="phone" class="control-label col-md-3">Phone</label>
                <div class="col-md-8">
                  <input type="text" name="contact[phone]" id="phone" class="form-control">
                </div>
              </div>
              <div class="form-group">
                <label for="name" class="control-label col-md-3">Address</label>
                <div class="col-md-8">
                  <textarea name="contact[address]" id="address" rows="3" class="form-control"></textarea>
                </div>
              </div>
              <div class="form-group">
                <label for="group" class="control-label col-md-3">Group</label>
                <div class="col-md-5">
                  <select name="contact[group_id]" id="group" class="form-control">
                    <option value="">Select group</option>
                    <% Group.all.each do |group| %>
                        <option value="<%= group.id %>"><%= group.name %></option>
                    <% end %>
                  </select>
                </div>
                <div class="col-md-3">
                  <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
                </div>
              </div>
              <div class="form-group" id="add-new-group" style="display: none;">
                <div class="col-md-offset-3 col-md-8">
                  <div class="input-group">
                    <input type="text" name="new_group" id="new_group" class="form-control">
                    <span class="input-group-btn">
                      <a href="#" class="btn btn-default">
                        <i class="glyphicon glyphicon-ok"></i>
                      </a>
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="fileinput fileinput-new" data-provides="fileinput">
                <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                  <img src="http://placehold.it/150x150" alt="Photo">
                </div>
                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
                <div class="text-center">
                  <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
                  <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-8">
            <div class="row">
              <div class="col-md-offset-3 col-md-6">
                <button type="submit" class="btn btn-primary">Save</button>
                <a href="#" class="btn btn-default">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "alert alert-#{type}" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "My Contact", root_path, class: "navbar-brand text-uppercase" %>
        </div>
        <!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <div class="nav navbar-right navbar-btn">
            <%= link_to new_contact_path, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-plus"></i> 
              Add Contact
            <% end %>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/_sidebar.html.erb
<div class="list-group">
  <% active = params[:group_id] == nil || params[:group_id].empty? ? 'active' : '' %>
  <%= link_to contacts_path, class: "list-group-item #{active}" do %>
    All Contact <span class="badge"><%= Contact.count %></span>
  <% end %>

  <% Group.all.each do |group| %>
    <% active = params[:group_id].to_i == group.id ? 'active' : '' %>
    <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
      <%= group.name %> <span class="badge"><%= group.contacts.count %></span>
    <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link rel="preload" href="assets/application-d77779e9daff98be297784b659581d4d020bfaff7ed0c18ecc57cd62a13f2cb5.css" as="style">
    <link rel="stylesheet" href="assets/application-d77779e9daff98be297784b659581d4d020bfaff7ed0c18ecc57cd62a13f2cb5.css">
  </head>

  <body>
    <!-- navbar -->
    <%= render 'layouts/navbar'%>

    <!-- content -->
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render 'layouts/sidebar' %>
        </div><!-- /.col-md-3 -->

        <div class="col-md-9">
          <%= render "layouts/messages" if !flash.empty? %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>